name: Run flow 01
on: [push]
jobs:
   hello_world_job:
      runs-on: linux-latest
      env:
         OENV_COMMITMESSAGE: ${{ github.event.head_commit.message }}
      name: Run flow 01 on jobs
      steps:
         - name: Check OENV_COMMITMESSAGE
           run: echo "$env:OENV_COMMITMESSAGE"
